=== OlehRadchenko/HiH/xml/fishing.dtd
<!ENTITY % EXPERIENCES "początkujący | średniozaawansowany | zaawansowany | ekspert | profesjonalista">
<!ENTITY % LOWISKO_CHOICE "rzeka | jezioro | morze">

<!ELEMENT wedkarstwo ( (wedkarze | zawody)* )>
<!ATTLIST wedkarstwo
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>

<!ELEMENT wedkarze (wedkarz+)>
<!ATTLIST wedkarze
    kraj   CDATA  #REQUIRED
    liczba CDATA  "0"
>

<!ELEMENT wedkarz (dane, sprzet?, polowy?)>
<!ATTLIST wedkarz
    id          ID    #REQUIRED
    doswiadczenie (%EXPERIENCES;) "początkujący"
    klub        CDATA "brak"
>

<!ELEMENT dane (imie, nazwisko, wiek, kontakt?)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT wiek (#PCDATA)>

<!ELEMENT kontakt (email, telefon?)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>

<!ELEMENT sprzet (wedka, kolowrotek, zylka?)>

<!ELEMENT wedka EMPTY>
<!ATTLIST wedka
    typ     CDATA #REQUIRED
    marka   CDATA "nieznana"
    dlugosc CDATA #IMPLIED
>

<!ELEMENT kolowrotek EMPTY>
<!ATTLIST kolowrotek
    marka CDATA "nieznana"
    model CDATA #IMPLIED
>

<!ELEMENT zylka EMPTY>
<!ATTLIST zylka
    grubosc      CDATA #REQUIRED
    wytrzymalosc CDATA "nieokreslona"
>

<!ELEMENT polowy (polow+)>

<!ELEMENT polow (gatunek, dlugoscNajwiekszejRyby?, wagaNajwiekszejRyby?, zdjecie*, lowisko?, opisPolowu?)>
<!ATTLIST polow
    data    CDATA #REQUIRED
    miejsce CDATA #IMPLIED
    pogoda  CDATA "nieznana"
>

<!ELEMENT gatunek (#PCDATA)>
<!ATTLIST gatunek
    rodzaj CDATA #IMPLIED
>

<!ELEMENT dlugoscNajwiekszejRyby (#PCDATA)>
<!ATTLIST dlugoscNajwiekszejRyby
    jednostka (mm | cm | m | ft) "cm"
    gatunek CDATA #IMPLIED
>

<!ELEMENT wagaNajwiekszejRyby (#PCDATA)>
<!ATTLIST wagaNajwiekszejRyby
    jednostka (g | kg | lb) "kg"
    gatunek CDATA #IMPLIED
>

<!ELEMENT zdjecie EMPTY>
<!ATTLIST zdjecie
    src  CDATA #REQUIRED
    opis CDATA "brak opisu"
>

<!ELEMENT lowisko ( %LOWISKO_CHOICE; )>

<!ELEMENT rzeka (#PCDATA)>
<!ATTLIST rzeka
    link CDATA #IMPLIED
>

<!ELEMENT jezioro (#PCDATA)>
<!ATTLIST jezioro
    link CDATA #IMPLIED
>

<!ELEMENT morze (#PCDATA)>
<!ATTLIST morze
    link CDATA #IMPLIED
>

<!ELEMENT opisPolowu (#PCDATA | miejsce | gatunek)*>
<!ELEMENT miejsce (#PCDATA)>

<!ELEMENT zawody (organizator, uczestnicy?, wyniki?, galeria?, linki?)>
<!ATTLIST zawody
    kraj CDATA "Polska"
    rok  CDATA #REQUIRED
>

<!ELEMENT organizator EMPTY>
<!ATTLIST organizator
    nazwa CDATA #REQUIRED
    kontakt CDATA #IMPLIED
>

<!ELEMENT uczestnicy (uczestnik+)>
<!ELEMENT uczestnik (imie, nazwisko, wiek)>
<!ATTLIST uczestnik
    id IDREF #REQUIRED
    doswiadczenie (%EXPERIENCES;) "początkujący"
    klub CDATA "brak"
>

<!ELEMENT wyniki (pozycja+)>
<!ELEMENT pozycja (uczestnikRef, zlowioneRyby?)>
<!ATTLIST pozycja
    miejsce CDATA #REQUIRED
    punkty  CDATA #REQUIRED
>

<!ELEMENT uczestnikRef EMPTY>
<!ATTLIST uczestnikRef
    id IDREF #REQUIRED
>

<!ELEMENT zlowioneRyby (#PCDATA)>

<!ELEMENT galeria (zdjecie+)>

<!ELEMENT linki (link+)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
    typ (regulamin | galeria | kontakt | inne) "inne"
>

=== OlehRadchenko/HiH/xml/fishing_withDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wedkarstwo SYSTEM "fishing.dtd">
<wedkarstwo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <wedkarze kraj="Polska" liczba="3">
        <wedkarz id="w1" doswiadczenie="średniozaawansowany" klub="Koło Gdańskie">
            <dane>
                <imie>Oleh</imie>
                <nazwisko>Radchenko</nazwisko>
                <wiek>19 lat</wiek>
                <kontakt>
                    <email>oleh.radchenko@example.com</email>
                    <telefon>+48 123 456 789</telefon>
                </kontakt>
            </dane>

            <sprzet>
                <wedka typ="spinning" marka="Shimano" dlugosc="2.7m"/>
                <kolowrotek marka="Daiwa" model="Revros 2500"/>
                <zylka grubosc="0.20mm" wytrzymalosc="6kg"/>
            </sprzet>

            <polowy>
                <polow data="2025-07-12" miejsce="Jezioro Żarnowieckie" pogoda="słoneczna">
                    <gatunek rodzaj="ryba drapieżna">Szczupak</gatunek>
                    <dlugoscNajwiekszejRyby jednostka="cm" gatunek="Szczupak">68</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby jednostka="kg" gatunek="Szczupak">2.5</wagaNajwiekszejRyby>
                    <zdjecie src="images/szczupak1.jpg" opis="Pierwszy połów lata"/>
                    <lowisko>
                        <jezioro link="https://pl.wikipedia.org/wiki/Jezioro_%C5%BBarnowieckie">Jezioro Żarnowieckie</jezioro>
                    </lowisko>
                    <opisPolowu> Wczoraj złowiłem pięknego 
                        <gatunek>szczupaka</gatunek> 
                        na jeziorze
                        <miejsce>Żarnowieckie</miejsce>.
                    </opisPolowu>
                </polow>

                <polow data="2025-08-02" miejsce="Rzeka Wisła" pogoda="pochmurna">
                    <gatunek rodzaj="ryba drapieżna">Sandacz</gatunek>
                    <dlugoscNajwiekszejRyby>BRAK DANYCH</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby>BRAK DANYCH</wagaNajwiekszejRyby>
                    <zdjecie src="images/sandacz1.jpg" opis="Sandacz z Wisły"/>
                    <lowisko>
                        <rzeka link="https://pl.wikipedia.org/wiki/Rzeka_Wis%C5%82a">Rzeka Wisła</rzeka>
                    </lowisko>
                    <opisPolowu> Podczas ostatniego wypadu na 
                        <miejsce>Wisłę</miejsce> 
                        udało mi się złowić <gatunek>sandacza</gatunek> o długości 54cm.
                    </opisPolowu>
                </polow>

                <polow data="2025-09-18" miejsce="Jezioro Łebsko" pogoda="wiatr">
                    <gatunek rodzaj="ryba biała">Okoń</gatunek>
                    <dlugoscNajwiekszejRyby jednostka="cm" gatunek="Okoń">25</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby jednostka="kg" gatunek="Okoń">0.3</wagaNajwiekszejRyby>
                    <zdjecie src="images/okon1.jpg" opis="Okoń z wrześniowego połowu"/>
                    <lowisko>
                        <morze link="https://pl.wikipedia.org/wiki/Morze_Bałtyckie">Morze Bałtyckie</morze>
                    </lowisko>
                    <opisPolowu> We wrześniu byłem na 
                        <miejsce>Łebsku</miejsce> 
                        i złowiłem kilka ładnych <gatunek>okoni</gatunek>.
                    </opisPolowu>
                </polow>
            </polowy>
        </wedkarz>

        <wedkarz id="w2" doswiadczenie="początkujący" klub="Koło Warszawskie">
            <dane>
                <imie>Anna</imie>
                <nazwisko>Kowalska</nazwisko>
                <wiek>23 lata</wiek>
                <kontakt>
                    <email>anna.kowalska@example.com</email>
                    <telefon>+48 123 456 791</telefon>
                </kontakt>
            </dane>
            <sprzet>
                <wedka typ="spławik" marka="Mikado" dlugosc="3.6m"/>
                <kolowrotek marka="Okuma" model="Trio 30"/>
                <zylka grubosc="0.18mm" wytrzymalosc="5kg"/>
            </sprzet>
            <polowy>
                <polow data="2025-06-20" miejsce="Jezioro Druzno" pogoda="deszczowa">
                    <gatunek rodzaj="ryba biała">Leszcz</gatunek>
                    <dlugoscNajwiekszejRyby jednostka="cm" gatunek="Leszcz">33</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby jednostka="kg" gatunek="Leszcz">REKORD</wagaNajwiekszejRyby>
                    <zdjecie src="images/leszcz.jpg" opis="Połów w deszczu"/>
                    <lowisko>
                        <jezioro link="https://pl.wikipedia.org/wiki/Jezioro_Druzno">Jezioro Druzno</jezioro>
                    </lowisko>
                    <opisPolowu> Wczoraj złowiłem pięknego 
                        <gatunek>leszcza</gatunek> 
                        na jeziorze
                        <miejsce>Druzno</miejsce>.
                    </opisPolowu>
                </polow>
            </polowy>
        </wedkarz>

        <wedkarz id="w3" doswiadczenie="ekspert" klub="Koło Poznańskie">
            <dane>
                <imie>Marek</imie>
                <nazwisko>Nowak</nazwisko>
                <wiek>35 lat</wiek>
                <kontakt>
                    <email>marek.nowak@example.com</email>
                    <telefon>+48 123 456 790</telefon>
                </kontakt>
            </dane>
            <sprzet>
                <wedka typ="gruntowa" marka="Dragon" dlugosc="3.9m"/>
                <kolowrotek marka="Penn" model="Battle III 4000"/>
                <zylka grubosc="0.25mm" wytrzymalosc="8kg"/>
            </sprzet>
            <polowy>
                <polow data="2025-07-01" miejsce="Rzeka Odra" pogoda="słoneczna">
                    <gatunek rodzaj="ryba drapieżna">Sum</gatunek>
                    <dlugoscNajwiekszejRyby jednostka="cm" gatunek="sum">REKORD</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby jednostka="kg" gatunek="sum">12.0</wagaNajwiekszejRyby>
                    <zdjecie src="images/sum.jpg" opis="Rekordowy sum z Odry"/>
                    <lowisko>
                        <rzeka link="https://pl.wikipedia.org/wiki/Rzeka_Odra">Rzeka Odra</rzeka>
                    </lowisko>
                    <opisPolowu> Podczas ostatniego wypadu na 
                        <miejsce>Odrę</miejsce> 
                        udało mi się złowić <gatunek>suma</gatunek> o długości 105cm.
                    </opisPolowu>
                </polow>
            </polowy>
        </wedkarz>
    </wedkarze>

    <zawody kraj="Polska" rok="2025">
        <organizator nazwa="Koło Wędkarskie Gdańsk" kontakt="+48577070237"/>
    
        <uczestnicy>
            <uczestnik id="w1" doswiadczenie="średniozaawansowany" klub="Koło Gdańskie">
                <imie>Oleh</imie>
                <nazwisko>Radchenko</nazwisko>
                <wiek>19 lat</wiek>
            </uczestnik>
            <uczestnik id="w6" doswiadczenie="początkujący" klub="Koło Warszawskie">
                <imie>Jan</imie>
                <nazwisko>Kowalski</nazwisko>
                <wiek>42 lata</wiek>
            </uczestnik>
        </uczestnicy>

        <wyniki>
            <pozycja miejsce="1" punkty="1540">
                <uczestnikRef id="w2"/>
                <zlowioneRyby>
                    sandacz okoń płoć
                </zlowioneRyby>
            </pozycja>
            <pozycja miejsce="2" punkty="980">
                <uczestnikRef id="w1"/>
                <zlowioneRyby>
                    szczupak leszcz okoń
                </zlowioneRyby>
            </pozycja>
        </wyniki>

        <galeria>
            <zdjecie src="images/start_zawodow.jpg" opis="Rozpoczęcie zawodów"/>
            <zdjecie src="images/zwyciezca.jpg" opis="Zwycięzca z trofeum"/>
            <zdjecie src="images/ryba_dnia.jpg" opis="Największa ryba zawodów"/>
        </galeria>

        <linki>
            <link typ="regulamin">https://pzw.pl/regulamin_zawody</link>
            <link typ="galeria">https://wedkarzegdansk.pl/galeria</link>
            <link typ="kontakt">https://wedkarzegdansk.pl/kontakt</link>
        </linki>
    </zawody>

    <wedkarze kraj="USA" liczba="3">
        <wedkarz id="w4" doswiadczenie="zaawansowany" klub="Texas Anglers Club">
            <dane>
                <imie>John</imie>
                <nazwisko>Smith</nazwisko>
                <wiek>42 lata</wiek>
                <kontakt>
                    <email>john.smith@example.com</email>
                </kontakt>
            </dane>
            <sprzet>
                <wedka typ="casting" marka="Abu Garcia" dlugosc="2.1m"/>
                <kolowrotek marka="Shimano" model="Curado 200"/>
                <zylka grubosc="0.25mm" wytrzymalosc="9kg"/>
            </sprzet>
            <polowy>
                <polow data="2025-07-04" miejsce="Lake Fork" pogoda="słoneczna">
                    <gatunek rodzaj="ryba drapieżna">Bass</gatunek>
                    <dlugoscNajwiekszejRyby jednostka="ft" gatunek="Bass">53</dlugoscNajwiekszejRyby>
                    <wagaNajwiekszejRyby jednostka="lb" gatunek="Bass">3.6</wagaNajwiekszejRyby>
                    <zdjecie src="images/bass1.jpg" opis="Bass z Texasu"/>
                    <lowisko>
                        <jezioro link="https://en.wikipedia.org/wiki/Lake_Fork_Reservoir">Lake Fork</jezioro>
                    </lowisko>
                    <opisPolowu> Świetny dzień nad <miejsce>Lake Fork</miejsce> – złowiłem potężnego <gatunek>bassa</gatunek>! </opisPolowu>
                </polow>
            </polowy>
        </wedkarz>

        <wedkarz id="w5" doswiadczenie="początkujący" klub="Florida Fishermen">
            <dane>
                <imie>Emily</imie>
                <nazwisko>Johnson</nazwisko>
                <wiek>27 lat</wiek>
                <kontakt>
                    <email>emily.johnson@example.com</email>
